// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFile() {
  return window['go']['main']['App']['ConvertFile']();
}

export function ConvertFiles(arg1, arg2) {
  return window['go']['main']['App']['ConvertFiles'](arg1, arg2);
}

export function PercentBar() {
  return window['go']['main']['App']['PercentBar']();
}
