// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertFile():Promise<void>;

export function ConvertFiles(arg1:string,arg2:string):Promise<void>;

export function PercentBar():Promise<void>;
